version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - '8080:80'

  backup:
    container_name: mysql_backup
    image: debian:bookworm-slim
    restart: always
    depends_on:
      - db
    volumes:
      - ./scripts-host:/scripts
      - ./backups-host:/backups
    entrypoint:
      - /bin/bash
      - -c
      - |
        apt-get update && apt-get install -y mariadb-client cron
        crontab /scripts/cronjob
        cron -f

volumes:
  mysql_data:
